services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_LOCAL_VERSION}
    container_name: ${ES_LOCAL_CONTAINER_NAME}
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./logs/elasticsearch:/usr/share/elasticsearch/logs

  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_LOCAL_VERSION}
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./logs/kibana:/usr/share/kibana/logs

  logstash:
    image: docker.elastic.co/logstash/logstash:${LOGSTASH_LOCAL_VERSION}
    container_name: logstash
    ports:
      - 5044:5044
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs/logstash:/usr/share/logstash/logs
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
      - ./logs/prometheus:/var/log/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - elasticsearch
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./logs/grafana:/var/log/grafana

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: log-api
    ports:
      - "5000:5000"
    volumes:
      - ./logs/apilogs:/app/logs